In [1]:
import numpy as np

In [2]:
mat_1=np.array([[2,3],[6,7]])

In [3]:
print(mat_1)

[[2 3]
 [6 7]]


In [5]:
#shape of a matrix(like 2x2)
mat_1.shape

(2, 2)

In [6]:
mat_2=np.array([[10,2,3],[2,3,4],[4,5,6]])
print(mat_2)

[[10  2  3]
 [ 2  3  4]
 [ 4  5  6]]


In [7]:
mat_2.shape

(3, 3)

Creating matrices with random values

In [8]:
random=np.random.rand(3,3)
print(random)

[[0.39023589 0.09365886 0.87681031]
 [0.37176314 0.44357841 0.51621524]
 [0.22788493 0.58252222 0.95155113]]


Creatin matrices with random Integers

In [9]:
rand_int=np.random.randint(100, size=(3,3)) # 100 is given to get values under 100
print(rand_int)

[[74 70 93]
 [73 95 86]
 [ 4 16 86]]


Creating matrices with the value one

In [11]:
mat_3=np.ones((2,3))
print(mat_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
mat_3=np.ones((2,3), dtype=int) # dtype means daat type
print(mat_3)

[[1 1 1]
 [1 1 1]]


Null matrix

In [14]:
null=np.zeros((2,3),dtype=int)
print(null)

[[0 0 0]
 [0 0 0]]


Identity matrix

In [17]:
identity=np.eye(3,3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Transpose of a matrix

In [18]:
#random integer values
a=np.random.randint(100,size=(4,5))
print(a)

[[21 56 39  5 70]
 [ 4 70 14 71 60]
 [93 84 30 38 71]
 [77 24 27 83 96]]


In [19]:
transpose_a=np.transpose(a)
print(transpose_a)

[[21  4 93 77]
 [56 70 84 24]
 [39 14 30 27]
 [ 5 71 38 83]
 [70 60 71 96]]


Matrix Operations

**Matrix Addition**

In [20]:
#two matrices with same shape
a=np.array([[1,2,3],[2,3,4]])
b=np.array([[2,3,4],[4,5,6]])
print(a)

[[1 2 3]
 [2 3 4]]


In [21]:
print(b)

[[2 3 4]
 [4 5 6]]


In [22]:
a.shape

(2, 3)

In [23]:
b.shape

(2, 3)

In [24]:
sum=a+b

In [25]:
print(sum)

[[ 3  5  7]
 [ 6  8 10]]


Create two matrices with random values

In [26]:
mat_1=np.random.randint(10,size=(2,2))
mat_2=np.random.randint(10,size=(2,2))
rand_sum=mat_1+mat_2
print(rand_sum)

[[11  9]
 [ 8 11]]


In [27]:
print(mat_1)

[[2 1]
 [8 4]]


In [28]:
print(mat_2)

[[9 8]
 [0 7]]


In [29]:
print(rand_sum)

[[11  9]
 [ 8 11]]


using function of numpy to add the matrices

In [30]:
sum_func=np.add(mat_1,mat_2)

In [31]:
print(sum_func)

[[11  9]
 [ 8 11]]


In [32]:
mat_3=np.random.randint(10,size=(2,2))
mat_4=np.random.randint(10,size=(2,3))
rand_sum_error=mat_3+mat_4
print(rand_sum_error)

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

We get the above as because they don't have same shape for two matrices. First one is different from the next one

Matrix Subtraction

In [33]:
a=np.array([[1,2,3],[2,3,4]])
b=np.array([[2,3,4],[4,5,6]])
diff=a-b
print(diff)

[[-1 -1 -1]
 [-2 -2 -2]]


In [35]:
func_diff=np.subtract(a,b)
print(func_diff)

[[-1 -1 -1]
 [-2 -2 -2]]


Multiplying a matrix by scalar

In [37]:
x=5
y=np.array([[2,3],[3,4]])
mul_scal=x*y
print(mul_scal)

[[10 15]
 [15 20]]


In [39]:
product=np.multiply(x,y)
print(product)

[[10 15]
 [15 20]]


Multiplying two matrices

In [40]:
mat_1=np.random.randint(5,size=(3,2))
mat_2=np.random.randint(5,size=(2,3))
print(mat_1)

[[1 1]
 [1 3]
 [1 0]]


In [41]:
print(mat_2)

[[3 1 3]
 [4 1 4]]


In [42]:
pro=np.dot(mat_1,mat_2)
print(pro)

[[ 7  2  7]
 [15  4 15]
 [ 3  1  3]]


In [43]:
pro.shape

(3, 3)

**Element wise multiplication in matrix**

In [52]:
mat_1=np.random.randint(5,size=(3,3))
mat_2=np.random.randint(5,size=(3,3))
print("Matrix 1\n",mat_1)
print("Matrix 2\n",mat_2)
multiply_element=np.multiply(mat_1,mat_2)
print("Resultant multiplication\n",multiply_element)

Matrix 1
 [[1 0 0]
 [4 3 2]
 [4 0 0]]
Matrix 2
 [[4 0 3]
 [1 1 2]
 [0 2 4]]
Resultant multiplication
 [[4 0 0]
 [4 3 4]
 [0 0 0]]
